---
title: "MitoRiboSeq Readlength distribution"
author: "Sophia Li"
date: "8/17/2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(cowplot)
library(RColorBrewer)
library(knitr)
library(ggrepel)
library(ineq)
opts_chunk$set(cache=TRUE, echo=TRUE, results="asis", message=FALSE)
```


```{r load_data}
data_path <- "/Volumes/Sophia_ResearchData/201800721_MitoRiboSeq_Serdpr_Chlorm_primerchange/data/read_length_count/Ch_2_readdistr.txt"
raw_data <- read_tsv(data_path)


# Load the mapping where we can turn IDs into names that are easily identifiable 
mito_info <-read_tsv("/Volumes/Sophia_ResearchData/201800721_MitoRiboSeq_Serdpr_Chlorm_primerchange/genome/Mito_GeneInfo.txt") 

raw_data <- raw_data %>% 
    left_join(.,mito_info %>% select(UCSC_id,AssociatedGeneName),by = c("gene_id"="UCSC_id")) %>% rename(gene_name = AssociatedGeneName) %>% select(gene_name,everything(),-gene_id) 

colnames = sapply(colnames(raw_data),function(x) stringr::str_replace_all(x,c("\\(" = "\\[", "\\)" = "\\]")))
colnames(raw_data) = colnames
```


```{r cumsum_plot, echo=FALSE}
data_long <- raw_data %>% gather(read_bin,counts,-c("gene_name","nuc_index","nuc_seq"))
colfunc <- colorRampPalette(c("#99BBFF", "#001A4D"))
pallete_color <- colfunc(length(unique(data_long$read_bin)))

data_sum <- data_long %>% group_by(gene_name,nuc_seq,nuc_index) %>% summarise(counts = sum(counts)) %>% mutate(read_bin = 'total')

data_long <- data_long %>% bind_rows(data_long,data_sum) %>% arrange(gene_name,nuc_index) %>% group_by(read_bin,gene_name) %>% mutate(frac_counts = counts/sum(counts),cum_fraccounts = cumsum(frac_counts),cum_counts = cumsum(counts)) 

plot_theme = list(geom_line(),scale_color_manual(values =c( pallete_color,"red")),
                  theme(strip.background = element_blank()),facet_wrap(~ gene_name, scales = "free"))

cum_counts_plot <- data_long  %>% ggplot(aes(x = nuc_index, y = cum_counts, col = read_bin,group = read_bin)) + plot_theme + 
  scale_y_continuous(labels = scales::scientific)

cum_fraccounts_plot <- data_long  %>% ggplot(aes(x = nuc_index, y = cum_fraccounts, col = read_bin,group = read_bin))+ plot_theme +
  scale_y_continuous(labels = scales::percent)

plot_basename = gsub(pattern = "_readdistr.txt","",basename(data_path))
save_plot(filename = paste0('readlen_distr/',plot_basename,'_cum_counts_plot.pdf'),cum_counts_plot,base_height = 12,base_width = 20)
save_plot(filename = paste0('readlen_distr/',plot_basename,'_cum_fraccounts_plot.pdf'),cum_fraccounts_plot,base_height = 12,base_width = 20)


```

